---
#
# Ansible managed
#
repository:
  description: Install and configure mssql on your system.
  homepage: https://buluma.github.io/
  topics: mssql, ansible, molecule, tox, playbook, hacktoberfest
